services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: email_sender_sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServerPwd123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: email_sender_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailpit:
    image: axllent/mailpit:latest
    container_name: email_sender_mailpit
    restart: always
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI Dashboard
    volumes:
      - mailpit_data:/data

volumes:
  sql_data:
  rabbitmq_data:
  mailpit_data:
