// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantManagement.Infrastructure.Persistence;

#nullable disable

namespace TenantManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TenantManagementDbContext))]
    [Migration("20260630142130_UpdateTenantDomainsTable")]
    partial class UpdateTenantDomainsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TenantManagement.Domain.Aggregates.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("TenantManagement.Domain.Aggregates.Tenant", b =>
                {
                    b.OwnsMany("TenantManagement.Domain.Entities.ApiKey", "ApiKeys", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<bool>("IsRevoked")
                                .HasColumnType("bit");

                            b1.Property<string>("KeyHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId");

                            b1.ToTable("TenantApiKeys", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsMany("TenantManagement.Domain.Entities.TenantDomain", "LinkedDomains", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsVerified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("IsVerified");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Domain");

                            b1.Property<string>("VerificationToken")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("VerificationToken");

                            b1.Property<DateTime?>("VerifiedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("VerifiedAt");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId");

                            b1.ToTable("TenantDomains", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("ApiKeys");

                    b.Navigation("LinkedDomains");
                });
#pragma warning restore 612, 618
        }
    }
}
